### ISSUE TITLE
improvement: add yaml `flow` to the info command

### ISSUE THREAD

**Issue by letFunny** [letFunny/chisel#9]
Make the output of the `info` command more readable by printing the entry attributes using the `flow` format. It is not trivial because if we add it to the map then the whole contents in placed inline and we want a separate line for each entry but the attributes should be in flow. I think we can do that by changing the YAML nodes directly: https://pkg.go.dev/gopkg.in/yaml.v3#Node

Current output example:
```yaml
package: mypkg
archive: ubuntu
slices:
    baz:
        essential:
            - libpkg_libs
            - mypkg_foo
            - mypkg_bar
    foo:
        contents:
            /etc/foo: {}
            /etc/foo-dir/:
                make: true
                mode: 0644
```
Desired:
```yaml
package: mypkg
archive: ubuntu
slices:
    baz:
        essential:
            - libpkg_libs
            - mypkg_foo
            - mypkg_bar
    foo:
        contents:
            /etc/foo:
            /etc/foo-dir/: {make: true, mode: 0644}
```
